BZ-1160683 NoSuchMethodError during init
When compiled by JDK 8 targeting Java 6 and then run on JDK 6 or 7 the
ConcurrentHashMap#keyset() method can fail because the return types
changed in Java 8. Using ConcurrentMap interface to resolve the issue.